import type {LanguageCode} from '../types/wiki';

export const uiCopy = {
    de: {
        welcomeTitle: 'Willkommen bei Scrollpedia',
        welcomeStart: 'Los geht\'s',
        welcomeExplanation: 'So funktioniert\'s',
        languageLabel: 'Wikipedia Sprache',
        aboutAria: 'Informationen zur App anzeigen',
        aboutTitle: 'Was ist Scrollpedia?',
        aboutEyebrow: 'Information',
        aboutDescription:
            'Scrollpedia ist eine TikTok-ähnliche App zum Scrollen von Content, nur dass der Content aus wissenswerten Wikipedia-Artikeln zu Themen wie Geschichte, Kunst, Wissenschaft und Technologie besteht.',
        aboutUsageTitle: 'Wie nutze ich Scrollpedia?',
        aboutUsageDescription:
            'Erst Themen wählen, dann wie in einer TikTok-ähnlichen App durch wissenswerte Wikipedia-Artikel scrollen. Mit „Mehr lesen“ öffnest du den ganzen Wikipedia-Artikel.',
        aboutInstallTitle: 'Scrollpedia als App installieren',
        aboutInstallIntro:
            'Scrollpedia lässt sich wie eine normale App installieren, damit du es direkt vom Home-Bildschirm aus öffnen kannst.',
        aboutInstallIos: 'iPhone / iOS',
        aboutInstallIosStep1: 'Scrollpedia in Safari öffnen.',
        aboutInstallIosStep2: 'Auf den Teilen-Button tippen.',
        aboutInstallIosStep3:
            'Im Menü nach unten scrollen und „Zum Home-Bildschirm“ antippen.',
        aboutInstallIosStep4: 'Mit „Hinzufügen“ bestätigen.',
        aboutInstallIosShareLabel: 'Teilen-Button',
        aboutInstallIosHomeLabel: 'Zum Home-Bildschirm',
        aboutInstallAndroid: 'Android',
        aboutInstallAndroidStep1: 'Scrollpedia in Chrome öffnen.',
        aboutInstallAndroidStep2: 'Auf das Drei-Punkte-Menü tippen.',
        aboutInstallAndroidStep3:
            'Im Menü nach unten scrollen und „Zum Startbildschirm hinzufügen“ oder „App installieren“ antippen.',
        aboutInstallAndroidStep4: 'Die Installation bestätigen.',
        aboutInstallAndroidMenuLabel: 'Drei-Punkte-Menü',
        aboutInstallAndroidHomeLabel: 'Installationsoption',
        aboutMeTitle: 'Über mich',
        aboutMeDescription: 'Erstellt von Noel Bromkamp.',
        aboutGithub: 'GitHub',
        aboutClose: 'Schließen',
        closeAboutAria: 'Informationsfenster schließen',
        genreHeading: 'Welche Themen interessieren dich?',
        popularLabel: 'Beliebte Wikipedia-Seiten',
        continue: 'Weiter',
        readMore: 'Mehr lesen',
        feedAriaLabel: 'Wikipedia Artikel Feed',
        feedUnavailableTitle: 'Feed nicht erreichbar',
        feedUnavailableDescription:
            'Wikipedia-Artikel konnten gerade nicht geladen werden.',
        noArticlesTitle: 'Keine passenden Artikel gefunden',
        noArticlesDescription:
            'Wähle andere Themen oder versuche es später erneut.',
        noPopularArticlesTitle: 'Keine meistgesehenen Artikel gefunden',
        noPopularArticlesDescription: 'Versuche es später erneut.',
        preparingTitle: 'Weitere Artikel werden vorbereitet',
        preparingDescription:
            'Es werden noch passende Wikipedia-Artikel gesammelt.',
        preparingPopularTitle: 'Meistgesehene Artikel werden vorbereitet',
        preparingPopularDescription:
            'Der aktuelle Feed mit meistgesehenen Artikeln wird vorbereitet.',
        loadingMore: 'Mehr Artikel werden geladen',
        loadingAriaLabel: 'Artikel werden geladen',
        loadingTitle: 'Artikel werden geladen',
        loadingPopularLine: 'Meistgesehene Artikel werden geladen...',
        loadingGenreSuffix: '-Artikel werden geladen...',
        loadingGenreFallback: 'Passende Artikel werden geladen...',
        changeGenres: 'Themen ändern',
        changeGenresAria: 'Zur Themen-Auswahl zurückkehren',
        changeSelection: 'Auswahl ändern',
        changeSelectionAria: 'Zur Feed-Auswahl zurückkehren',
        backToFeed: 'Zurück',
        backToFeedAria: 'Zurück zum Feed',
        backToWelcomeAria: 'Zum Welcome Screen zurückkehren',
        articleLoading: 'Artikel wird geladen...',
        articleLoadError:
            'Der vollständige Artikel konnte nicht geladen werden.',
        readOnWikipedia: 'Auf Wikipedia weiterlesen',
        enableDarkMode: 'Dark Mode aktivieren',
        enableLightMode: 'Light Mode aktivieren',
        galleryImageLabel: 'Bild',
    },
    en: {
        welcomeTitle: 'Welcome to Scrollpedia',
        welcomeStart: 'Get started',
        welcomeExplanation: 'How to use',
        languageLabel: 'Wikipedia language',
        aboutAria: 'Show app information',
        aboutTitle: 'What is Scrollpedia?',
        aboutEyebrow: 'Information',
        aboutDescription:
            'Scrollpedia is a TikTok-like app for scrolling content, except the content is informative Wikipedia articles about topics like history, art, science, and technology.',
        aboutUsageTitle: 'How do I use Scrollpedia?',
        aboutUsageDescription:
            'Choose your topics, then scroll through informative Wikipedia articles in a TikTok-like feed. Tap "Read more" when you want the full Wikipedia article.',
        aboutInstallTitle: 'Install Scrollpedia as an app',
        aboutInstallIntro:
            'Scrollpedia can be installed like a normal app, so you can open it directly from your home screen.',
        aboutInstallIos: 'iPhone / iOS',
        aboutInstallIosStep1: 'Open Scrollpedia in Safari.',
        aboutInstallIosStep2: 'Tap the Share button.',
        aboutInstallIosStep3:
            'Scroll the menu and tap "Add to Home Screen".',
        aboutInstallIosStep4: 'Tap "Add" to confirm.',
        aboutInstallIosShareLabel: 'Share button',
        aboutInstallIosHomeLabel: 'Add to Home Screen',
        aboutInstallAndroid: 'Android',
        aboutInstallAndroidStep1: 'Open Scrollpedia in Chrome.',
        aboutInstallAndroidStep2: 'Tap the three-dot menu.',
        aboutInstallAndroidStep3:
            'Scroll the menu and tap "Add to Home screen" or "Install app".',
        aboutInstallAndroidStep4: 'Confirm the installation.',
        aboutInstallAndroidMenuLabel: 'Three-dot menu',
        aboutInstallAndroidHomeLabel: 'Install option',
        aboutMeTitle: 'About me',
        aboutMeDescription: 'Created by Noel Bromkamp.',
        aboutGithub: 'GitHub',
        aboutClose: 'Close',
        closeAboutAria: 'Close about dialog',
        genreHeading: 'What topics are you interested in',
        popularLabel: 'Popular Wikipedia Pages',
        continue: 'Continue',
        readMore: 'Read more',
        feedAriaLabel: 'Wikipedia article feed',
        feedUnavailableTitle: 'Feed unavailable',
        feedUnavailableDescription:
            'Wikipedia articles could not be loaded right now.',
        noArticlesTitle: 'No matching articles found',
        noArticlesDescription:
            'Choose different topics or try again later.',
        noPopularArticlesTitle: 'No most-viewed articles found',
        noPopularArticlesDescription: 'Try again later.',
        preparingTitle: 'Preparing more articles',
        preparingDescription:
            'More matching Wikipedia articles are being gathered.',
        preparingPopularTitle: 'Preparing most-viewed articles',
        preparingPopularDescription:
            'The current most-viewed articles feed is being prepared.',
        loadingMore: 'Loading more articles',
        loadingAriaLabel: 'Articles are loading',
        loadingTitle: 'Articles are loading',
        loadingPopularLine: 'Most-viewed articles are loading...',
        loadingGenreSuffix: ' articles are loading...',
        loadingGenreFallback: 'Matching articles are loading...',
        changeGenres: 'Change topics',
        changeGenresAria: 'Return to topic selection',
        changeSelection: 'Change selection',
        changeSelectionAria: 'Return to feed selection',
        backToFeed: 'Back',
        backToFeedAria: 'Back to feed',
        backToWelcomeAria: 'Return to welcome screen',
        articleLoading: 'Loading article...',
        articleLoadError: 'The full article could not be loaded.',
        readOnWikipedia: 'Continue on Wikipedia',
        enableDarkMode: 'Enable dark mode',
        enableLightMode: 'Enable light mode',
        galleryImageLabel: 'Image',
    },
} satisfies Record<LanguageCode, Record<string, string>>;
